[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "shvit_enhancement"
version = "0.1.0"
dependencies = [
    "torch",
    "torchvision"
    # other dependencies
]
